### ISSUE TITLE
Solving ODE with time-dependent parameters

### ISSUE THREAD

**Issue by AhmedAlreweny** [JuliaDiffEq/DiffEqDocs.jl#298]
Hello, 

I was trying to solve a system of ODEs using the ODE solver with constant coefficient, and it worked fine. Now I am trying to solve the same problem with time-dependent coefficients (generated by solving another ODE system). How can I go about solving this?

**Comment by ChrisRackauckas** [comment]
Just use the `t` in the model definition. Let me know if you have any difficulties with that. I am not sure how to answer more, so I am closing this because there's not anything further on the documentation, but feel free to continue chatting.

BTW, if you'd like to get quick help via chats, you can join the Julialang slack: https://slackinvite.julialang.org/ and the #diffeq-bridged channel can be helpful for these kinds of things.
