### ISSUE TITLE
Learning curve with parameter estimation

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqDocs.jl#3]
This example is running fine. Can you extend the example to all four parameters to be estimated instead of just a=>. It should be b=>, c=>, d=> but it does not run further down.

Further down, using optim. This is going to be an extremely useful step for testing different optimization methods. What is the proper syntax for introducing autodiff? It should be:

BFGS(), OptimizationOptions(autodiff = true) or 
Newton(), OptimizationOptions(autodiff = true)

but I cannot get it to work.

Finally, running result = optimize(cost_function, [1.02], BFGS()) gives the following warning:
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.

Where are the parameter twitches for these?

Otherwise, excellent work to focus on effectiveness on the key steps.

**Comment by ChrisRackauckas** [comment]
>Finally, running result = optimize(cost_function, [1.02], BFGS()) gives the following warning:

This is explained in the docs already:

>Note that we set maxiters so that way the differential equation solvers would error more quickly when in bad regions of the parameter space, speeding up the process. 

You want it to hit maxiters in the "bad" regions to speed it up.

>Further down, using optim. This is going to be an extremely useful step for testing different optimization methods. What is the proper syntax for introducing autodiff?

This is explained in the Optim documentation.

http://www.juliaopt.org/Optim.jl/latest/user/config/

But right now the args all go to the DiffEq solver. I need a way to send some of the kwargs to Optim and some to DiffEq

**Comment by ChrisRackauckas** [comment]
>This example is running fine. Can you extend the example to all four parameters to be estimated instead of just a=>. It should be b=>, c=>, d=> but it does not run further down.

I chose a single parameter because Brent's method requires a single parameter. The other methods should work with more parameters. Did they not?

**Comment by finmod** [comment]
The explanation of the warning is fine.

The autodiff syntax would be fine but the args all go to the DiffEq solver for now. So it cannot be tested right now.

For two or more parameters, not working with any other Goldensection(), LBFGS() or other. The one parameter example is trivial, several or all parameters are much more relevant t any work in this field. Can you pls extend this example to more than one? Thanks

**Comment by ChrisRackauckas** [comment]
>For two or more parameters, not working with any other Goldensection(), LBFGS() or other.

This seems to be a separate issue. It seems like it's just not robust to being in bad parameter ranges. I gave it a try and it has an indexing error when max iters is reached in this case. Makes me question how it worked before. I wonder, what's the right way to handle that? It's erroring because it didn't reach every timepoint to compare to data, so when it computes the error at each timepoint it's there aren't enough indices. Instead I need to make it extrapolate, which will be a natural way to have to produce large errors.

**Comment by finmod** [comment]
Yes, there are two issues. I would advise to sort out the parameter estimation problem through the
build_lsoptim_objective(prob,tspan,t,data;kwargs...) route. Presumably, everything inside Least SquaresOptim is running smootly so this is just a question of passing correctly arguments in and out.
This deals with simple even if sparse nonlinear regression which is also Maximum Likelihhod if the errors are Gaussian.

Then we can return to the specifics of the integrator and cost function in 
build_optim_objective(prob,tspan,t,data;loss_func = L2DistLoss,kwargs...)
This deals with generalized profiling approaches including data fit and model fit. For identical input, the latter should produce identical results to the lsoptim, perhaps with different efficiency.

**Comment by ChrisRackauckas** [comment]
Actually, these can probably be put together via some `build_optimization_objective(prob,tspan,t,data;loss_func = L2DistLoss,kwargs...)` function which handles both cases. LsqFit still needs its own because it needs `f(t,p)` instead of `f(p)`. But putting them together will make things a little easier.

However, the current problem is still with error handling. The actual issue is that the optimization algorithms can send the parameters into a "bad area", which then causes the ODE to diverge. What should the cost for the cost function be in those cases? Inf? Then I am not sure if it's linear, or how the optimization algorithm will respond.

To put it more clearly, there are some parameters where an ODE will diverge. This is what happens in the LotkaVolterra example if you push it too far (so it's a good test case!). Say we want to test the data at `t=1:100`. The objective function will try to solve with these bad parameters, diverge at say `t=11.5`, and then when you try to test the numerical solution vs the data, you are calculating the difference between a size 100 array and a size 11 array which is why it errors. Truncating to use the error in the first 11 parts may work, because the solution diverges and therefore this error will be a large value, but I am not sure if this will give odd behavior (maybe it will find out that it can get zero error by diverging instantly!).

**Comment by ChrisRackauckas** [comment]
Because of the way the common solver interface works, every solver accepts `kwargs...`, and the kwargs don't overlap with those of LsqFit, so that had a simple fix of just passing the args to both. 

I added robustness by filling unstable paths with NaNs. Multivariate examples should work and I have added them to my tests. Of course, you have to start reasonably close to the correct answer since everything employed here is a local method. Future work would have to either do better implementations of the overarching algortihm, or link to MathProgBase.jl/JuMP to get a hold of some global minimization techniques.
