### ISSUE TITLE
Plotting module used for paramest_notfit.png

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqDocs.jl#8]
In the JuliaDiffEq ecosystem, can you please indicate which plotting module and commands were used to produce paramest_notfit.png and paramest_fit.png?

It is fine to publish the .png in the .md files but it would be good for users to be able to produce their own plots. Using Plots; plotly() or gr() do not produce the same published graph.

Thanks.

**Comment by ChrisRackauckas** [comment]
It's just using `plot!(sol)` to add plots of the solution plus `scatter!(data)` to do a scatter plot of the training data. You can see it in an old version of the tests here:

https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/blob/fa6223ba14752791ed8875d29f2e5c2a91cf077c/test/runtests.jl

I kind of think that's just a general Plots.jl + plot recipe usage thing which shouldn't be needed that far in the docs, but if you think it's needed I'll accept a PR which adds these commands.

In general, I think there should be a nicer way to handle this rather than just direct plotting and mutating plots. Some kind of recipe for parameter estimation results? Also a way to plot how it converges? I had the idea as a Google Summer of Code project, but took it down because I don't think that would be a long coding project, and more of a "what's the right API / result?" type of discussion.

**Comment by finmod** [comment]
Solved. I am elaborating a notebook for the various methods of estimating parameters and I insert the commands you gave above in the md text presenting the plots. This allows the user to reproduce the plots locally or move one.
Of course, we will exchange the "parameter estimation" notebook when ready.
